repository:
  path: github.com/timonwong/prometheus-webhook-dingtalk
go:
  version: 1.8.3
  cgo: false
build:
  binaries:
    - name: prometheus-webhook-dingtalk
      path: ./cmd/prometheus-webhook-dingtalk
  flags: -a -tags 'netgo static_build'
  ldflags: |
    -s
    -X {{repoPath}}/vendor/github.com/prometheus/common/version.Version={{.Version}}
    -X {{repoPath}}/vendor/github.com/prometheus/common/version.Revision={{.Revision}}
    -X {{repoPath}}/vendor/github.com/prometheus/common/version.Branch={{.Branch}}
    -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
crossbuild:
  platforms:
    - linux/amd64
    - linux/386
    - darwin/amd64
    - darwin/386
    - windows/amd64
    - windows/386
    - netbsd/amd64
    - netbsd/386
    - linux/arm
    - linux/arm64
    - netbsd/arm
