repository:
  path: github.com/timonwong/prometheus-webhook-dingtalk
go:
  version: 1.18
  cgo: false
build:
  binaries:
    - name: prometheus-webhook-dingtalk
      path: ./cmd/prometheus-webhook-dingtalk
  flags: -a -tags netgo,builtinassets
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
    - contrib
    - config.example.yml
crossbuild:
  platforms:
    - darwin
    - windows/amd64
    - windows/arm64
    - windows/386
    - linux/amd64
    - linux/arm
    - linux/arm64
